### ISSUE TITLE
Integration tests should use transactions for database rollback

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/catwatch#25]

**Comment by rwitzel** [comment]
I personally strongly prefer tests without transaction rollbacks.

Reasons:
1. Other persistence layer is possible which increases the use of the project.
   At the moment CatWatch can be easily adapted to use MongoDB instead of PostGreSQL (via Spring Data MongoDB). If the tests are transactional this is probably no longer the case because MongoDB does not support such a rollback.
2. Integration tests without transaction rollback test the application as it is. Some errors are not be revealed by tests with transaction rollback.
3. It makes the application and tests more robust when they are able to deal with "dirty" database contents from the beginning.

**Comment by rwitzel** [comment]
Closed due to the abovementioned reasons.
