### ISSUE TITLE
Bug: Not all repositories of the organizations are listed

### ISSUE THREAD

**Issue by rwitzel** [zalando/catwatch#5]
The current code base fetches not all repositories (GHOrganization.listRepositories() returns only the first page).

**Comment by jbellmann** [comment]
Is this really an bug, or was this fixed but not closed? I ask because of the site shows 229 repositories. I tested with 'listRepoTest' and got the following result:

```
15:20:41.203 [main] INFO  o.z.c.b.github.ListRepositoriesTest - PUBLIC REPOS: 188
15:20:41.208 [main] INFO  o.z.c.b.github.ListRepositoriesTest - PUBLIC_REPOS_NO_FORK: 155
```

So 155 just for 'zalando' + 'techmonkeys (12)' + 'stups (ca. 60)' = 227. That is near by.
For me 'GHOrganization.listRepositories()' seems to work. The 'listRepository()'-method is called without any argument about page-size, so it uses 30 as default and fetches at least more than 6 pages to reach 188 public repos. Don't forget the private repos are filtered in the afterwards.

Can someone review this issue or close it?

**Comment by rwitzel** [comment]
https://github.com/zalando/riptide is a Zalando open source project but not listed on the page. Thus there is somewhere a bug.

**Comment by rwitzel** [comment]
1. There was a fix added to the code (2015 August 5) to make sure that snapshot dates are same for all organizations. Could it be that this code was never deployed so that the problem persisted?

Thus my question: Alexander, could you reproduce the problem with the current code base?
1. The last snapshot date could be different among organizations only if the data of these organizations are not fetched, right? But when can this happen? The data of the organizations are always fetched at the same time, triggered by the same piece of code.

**Comment by AlexanderYastrebov** [comment]
Last snapshot should be calculated with regard of organization. If there were no problems, this snapshot date would be the same for all organizations. 

Currently catwatch does not fetch zalando data since 1st of september due to #17
