### ISSUE TITLE
A different approach for the Catwatch formula

### ISSUE THREAD

**Issue by lasomethingsomething** [zalando/catwatch#51]
Does the Catwatch formula used to calculate rankings factor in the number of commits? I would advise dropping this from the formula because it doesn't necessarily indicate better project quality. Projects like Zappr that are really useful aren't showing up near the top of the rankings -- would prefer that they did.

**Comment by fmueller** [comment]
For me, there are two ways to approach this issue:
- Drop commits entirely from ranking formula
- Add time-based factor to formula: commits should be ranked by recency (the older a commit is, the less he counts in ranking)

**Comment by hjacobs** [comment]
Please also consider #46 (penalty for less than two maintainers).

**Comment by lasomethingsomething** [comment]
@fmueller The latter would work for me.

**Comment by lasomethingsomething** [comment]
@hjacobs Not sure I follow. Are you suggesting that we apply points based on the number of maintainers?

**Comment by hjacobs** [comment]
@LappleApple not really adding points, but just penalizing projects with less than two maintainers (projects should not be able to just get more points by adding more maintainers). See my example in #46 (subtracting 100 points if the number of maintainers is lower than 2)

**Comment by lasomethingsomething** [comment]
@hjacobs  Got it. That's a good idea. I would use it and @fmueller's -- but that's just one opinion. Going to add this to our list of potential stories, but please continue contributing your thoughts/ideas for changes here so we paint the most complete picture of our options as we tweak

**Comment by fmueller** [comment]
Simple idea for 'time-based commit points: scan last 5 commits of a project and add penalty for each day it is old. My 2 cents.

**Comment by mtrovo** [comment]
I think commit dates should not be taken as a linear variable (like -1 for each day) as I think the correlation should be more like a long tail with a fast decreasing significance. I would suggest instead to count with the ratio of `commits / age of repository` as younger repositories with less commits can be seen as more active than older ones with more commits. Another simpler alternative is to get the last commit date and make it an exponential penalty, say `1.2^(number of days since last commit)`.

Also there's some other variables I would consider with different factors:
- (ratio of followers + stars) / age of repository
- number of maintainers
- number of merged pull requests
- ratio of issues closed / open

Maybe add all of them and play with their significance to see how it would work.

**Comment by jmcs** [comment]
What about for every commit add `1/(log(1+time_factor))` to the score.

Where `time_factor = (commit_timestamp-oldest_commit_timestamp)/(current_timestamp-oldest_commit_timestamp)`.

**Comment by fmueller** [comment]
The log formular by @jmcs looks quite simple and promising. And it should be easy to implement.

**Comment by fmueller** [comment]
@mtrovo By adding to many factors you'll increase complexity by magnitudes. I'd be careful with this. For instance, if you consider issues you also should consider situation where a project is new and many issues are opened til closed and so on.

**Comment by mtrovo** [comment]
@fmueller I was just showing some parameters that I see significance on the ranking, not requiring to add all of them together. 

@jmcs I think your formula is a long tail with more significance on the oldest commits, I think the correct time_factor should look like this:
`time_factor = (curent_timestamp-commit_timestamp)/(current_timestamp-oldest_commit_timestamp)`

And anyway it's done I think any formula you can create over numbers provided by github api is better than having to read all commit history to compute a relevance.

**Comment by rbobin** [comment]
Fixed with https://github.com/zalando/catwatch/pull/53
