### ISSUE TITLE
Project box visuals

### ISSUE THREAD

**Issue by semonte** [zalando/catwatch#56]
I think that the boxes have too thin borders, and border-top is almost invisible when using dark colors. We could use wider border and perhaps remove the top-border, for example:

![image](https://cloud.githubusercontent.com/assets/1151536/16142469/dc6aaa6e-3465-11e6-9182-853412658a82.png)

For reference, current version:

![image](https://cloud.githubusercontent.com/assets/1151536/16142485/0575e536-3466-11e6-8dbe-a68dc3fcc1a5.png)

What say you?

**Comment by rbarilani** [comment]
I @semonte can you move this issue here: https://github.com/zalando-incubator/zalando.github.io-dev/issues...

Catwatch is "just" the REST API that zalando.github.io page use to fetch data.

Anyway I like your proposal. Maybe directly open a PR to https://github.com/zalando-incubator/zalando.github.io-dev against the `dev` branch. Cheers
